### ISSUE TITLE
Pages - 100%

### ISSUE THREAD

**Issue by VitorGouveia** [EsquemaFlorescer/neo-expensive#17]
# Pages
- [x] Home 
- [x] Login 
- [x] Register
- [x] Profile
-----
- [x] Support 
- [x] Who We Are
-----
- [x] Cart
- [x] Checkout
-----
- [x] Informatics (Informática)
- [x] Console (Consoles)
-----

**Comment by AtomicFeasT** [comment]
Done, lesss gooo
